name: GlassPain
author: Endermanbugzjfc
version: 1.0.0
api: 4.0.0
main: Endermanbugzjfc\GlassPain\GlassPain
src-namespace-prefix: Endermanbugzjfc\GlassPain\GlassPain
website: https://github.com/Endermanbugzjfc/GlassPain

depend:
  - InfoAPI
